ok:
  http:
    connect-timeout: 60
    read-timeout: 60
    write-timeout: 60
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
    # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300

thread:
  pool:
    # 核心线程数（默认线程数）
    core-pool-size: 500
    # 最大线程数
    max-pool-size: 1000
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 缓冲队列数
    queue-capacity: 1500
    # 线程池名前缀
    thread-name-prefix: "Async-Service-"